import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '../componets/UI/ButtonStyles';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello world</h1>
        <Button>Create an Account</Button>
      </main>
    </>
  );
};

export default Home;
